apiVersion: skaffold/v2beta23
kind: Config
build:
  local:
    useBuildkit: true
  artifacts:
    - image: keptncontrib/argo-service
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    flags:
      upgrade: ["--reuse-values", "--install"]
    releases:
      - name: argo-service # needs to be the same name as currently used (check via helm ls -n keptn)
        namespace: keptn # needs to be the same namespace as where the helm-chart is currently deployed
        # upgradeOnChange: true
        # recreatePods: false # don't recreate all pods
        artifactOverrides:
          image: keptncontrib/argo-service
        imageStrategy:
          helm: { }
        overrides:
          distributor:
            image:
              tag: 0.10.0
          resources:
            limits:
              memory: 512Mi
        chartPath: chart
